Or 1927 update listener withdrawal flow for thanos titan app listen on optimism portal2 and l2 to l1 message passer
tokamak-network/tokamak-thanos-event-listener pull request #18
Opened 2024-11-06 03:54 UTC by nguyenzung

Handle withdrawal event in primitive contracts: OptimismPortal and L2ToL1MessagePasser

Thank you!

2024-11-06 04:09 UTC, nguyenzung commented
I think we should put notifier in the callback function. It is great if handing notifier by the callback, because we don't need to push message to Slack everytime an event occurs. 

https://github.com/tokamak-network/tokamak-thanos-event-listener/blob/OR-1927-update-listener-withdrawal-flow-for-thanos-titan-app-listen-on-OptimismPortal2-and-L2ToL1MessagePasser/internal/pkg/listener/request.go#L49

2024-11-06 05:37 UTC, 0x6e616d requested changes

2024-11-06 05:37 UTC, 0x6e616d commented on internal/app/thanos-notif/withdrawal.go
> +	title := fmt.Sprintf("[" + p.cfg.Network + "] [Withdrawal Finalized]")
This line must be "Withdrawal Initiated", right?

2024-11-06 05:37 UTC, 0x6e616d commented
Please consider at this case: we withdraw by the standard bridge, and we are listening to two events:
- `MessagePassed` from the `L2ToL1MessagePasser` contract
- `WithdrawalInitiated` from the `L2StandardBridge` contract

2024-11-06 06:07 UTC, nguyenzung commented on internal/app/thanos-notif/withdrawal.go
> +	title := fmt.Sprintf("[" + p.cfg.Network + "] [Withdrawal Finalized]")
Totally correct. Thank you!

2024-11-06 06:11 UTC, nguyenzung commented
> Please consider this case: we withdraw by the standard bridge, and we are listening to two events:
> 
> * `MessagePassed` from the `L2ToL1MessagePasser` contract
> * `WithdrawalInitiated` from the `L2StandardBridge` contract
> 
> -> So, we can duplicate the events from the same tx.

These event actually are not the same. MessagePassed is used for all withdrawals. WithdrawalInitiated is used with only withdrawal that triggered by L2StandardBridge, including some other event info.

2024-11-06 06:38 UTC, 0x6e616d commented
> > Please consider this case: we withdraw by the standard bridge, and we are listening to two events:
> > 
> > * `MessagePassed` from the `L2ToL1MessagePasser` contract
> > * `WithdrawalInitiated` from the `L2StandardBridge` contract
> > 
> > -> So, we can duplicate the events from the same tx.
> 
> These event actually are not the same. MessagePassed is used for all withdrawals. WithdrawalInitiated is used with only withdrawal that triggered by L2StandardBridge, including some other event info.

Yes, they aren't same but we will trigger two event for only one event `withdraw initiated` when bridging through the L2StandardBridge contract.

2024-11-06 06:49 UTC, nguyenzung commented
> > > Please consider this case: we withdraw by the standard bridge, and we are listening to two events:
> > > 
> > > * `MessagePassed` from the `L2ToL1MessagePasser` contract
> > > * `WithdrawalInitiated` from the `L2StandardBridge` contract
> > > 
> > > -> So, we can duplicate the events from the same tx.
> > 
> > 
> > These event actually are not the same. MessagePassed is used for all withdrawals. WithdrawalInitiated is used with only withdrawal that triggered by L2StandardBridge, including some other event info.
> 
> Yes, they aren't the same but we will trigger two notifications every time `withdraw initiated` when bridging through the L2StandardBridge contract.

I understood your opinion. I mean we can keep these events. Because StandardBridges have important events needed to notify, and the same thing for our Portals. 

What do you think about it? @steven94kr @theo-learner @ohbyeongmin @xxeonge

2024-11-06 07:29 UTC, steven94kr commented
I think we can listen for Event but there should be only one notification.

It can be very confusing to receive two notifications for your deposit.

I think it would be best if you could find a way. However, if it is difficult to parse MassagePasser events, it may be a good idea to use the current version.

2024-11-06 07:45 UTC, nguyenzung commented
> I think we can listen for Event but there should be only one notification.
> 
> It can be very confusing to receive two notifications for your deposit.
> 
> I think it would be best if we could find a way. However, if it is difficult to parse MassagePasser events, it may be a good idea to use the current version.

I think it could be a good approach. Let me think about it. Thank you!

2024-11-13 07:22 UTC, nguyenzung commented
Hi @steven94kr @0x6e616d @theo-learner 
Please check my updates

2024-11-14 03:33 UTC, theo-learner approved these changes
Thank you so much, Brave!

2024-11-14 03:40 UTC, merged